create table emp 
 (	empid	number	,
	name	string	,
	fname	string	,
	mname	string	,
	lname	string	,
	gender	string	,
	email	string	,
	fatname	string	,
	motname	string	,
	motmname	string	,
	dbo	date	,
	dobt	time	,
	age	number	,
	weight	number	,
	doj	date	,
	qoj	string	,
	hoj	string	,
	yoj	number	,
	moj	number	,
	mojn	string	,
	mojsn	string	,
	dojd	number	,
	dojw	string	,
	dojsd	string	,
	tenure	number	,
	sal	number	,
	hikeper	string	,
	ssn	string	,
	pno	string	,
	place	string	,
	ctry	string	,
	city	string	,
	state	string	,
	zip	string	,
	region	string	,
	uname	string	,
	passwd	string	);


insert into emp_ins
       (empid   , name    , fname   , mname   , lname   , gender  , email   , fatname , motname , motmname, dbo     , dobt    , age     , weight  , doj     ,
        qoj     , hoj     , yoj     , moj     , mojn    , mojsn   , dojd    , dojw    , dojsd   , tenure  , sal     , hikeper , ssn     , pno     , place   ,
        ctry    , city    , state   , zip     , region  , uname   , passwd  );
